using printf(string ...): int;

printf("%f\n", 2.0 + 0.0);
printf("%f\n", 2.0 + 10000000.0);
printf("%f\n", 2.0 + 2.0);
printf("%f\n", 0.0 + 0.0);
printf("%f\n", 2.0 - 10000000.0);
printf("%f\n", 10.0 - 5.0);
printf("%f\n", 10.0 - 10.0);
printf("%f\n", 0.0 - 0.0);
printf("%f\n", 0.0 * 0.0);
printf("%f\n", 10.0 * 0.0);
printf("%f\n", 10.0 * 10.0);
printf("%f\n", 10.0 * 5.0);
printf("%f\n", 10.0 / 5.0);
printf("%f\n", 10.0 / 2.0);
printf("%f\n", 10.0 / 100.0);
printf("%f\n", 0.0 / 1.0);
