using printf(string ...): int;

printf("%d\n", 2 + 0);
printf("%d\n", 2 + 10000000);
printf("%d\n", 2 + 2);
printf("%d\n", 0 + 0);
printf("%d\n", 2 - 10000000);
printf("%d\n", 10 - 5);
printf("%d\n", 10 - 10);
printf("%d\n", 0 - 0);
printf("%d\n", 0 * 0);
printf("%d\n", 10 * 0);
printf("%d\n", 10 * 10);
printf("%d\n", 10 * 5);
printf("%d\n", 10 / 5);
printf("%d\n", 10 / 2);
printf("%d\n", 10 / 100);
printf("%d\n", 0 / 1);
