using printf(string ...): int;

if 1 == 1 then printf("yes\n") else printf("no\n");
if 1 != 1 then printf("yes\n") else printf("no\n");
if 1 == 2 then printf("yes\n") else printf("no\n");
if 1 != 2 then printf("yes\n") else printf("no\n");
if 1 < 2  then printf("yes\n") else printf("no\n");
if 2 < 1  then printf("yes\n") else printf("no\n");
if 1 > 2  then printf("yes\n") else printf("no\n");
if 2 > 1  then printf("yes\n") else printf("no\n");
if 1 <= 2 then printf("yes\n") else printf("no\n");
if 2 <= 1 then printf("yes\n") else printf("no\n");
if 1 <= 1 then printf("yes\n") else printf("no\n");
if 1 >= 2 then printf("yes\n") else printf("no\n");
if 2 >= 1 then printf("yes\n") else printf("no\n");
if 1 >= 1 then printf("yes\n") else printf("no\n");
