using puts(string): int;

if 1.0 == 1.0 then puts("yes") else puts("no");
if 1.0 != 1.0 then puts("yes") else puts("no");
if 1.0 == 2.0 then puts("yes") else puts("no");
if 1.0 != 2.0 then puts("yes") else puts("no");
if 1.0 < 2.0  then puts("yes") else puts("no");
if 2.0 < 1.0  then puts("yes") else puts("no");
if 1.0 > 2.0  then puts("yes") else puts("no");
if 2.0 > 1.0  then puts("yes") else puts("no");
if 1.0 <= 2.0 then puts("yes") else puts("no");
if 2.0 <= 1.0 then puts("yes") else puts("no");
if 1.0 <= 1.0 then puts("yes") else puts("no");
if 1.0 >= 2.0 then puts("yes") else puts("no");
if 2.0 >= 1.0 then puts("yes") else puts("no");
if 1.0 >= 1.0 then puts("yes") else puts("no");
