using puts(string): int;

if 1 == 1 then puts("yes") else puts("no");
if 1 != 1 then puts("yes") else puts("no");
if 1 == 2 then puts("yes") else puts("no");
if 1 != 2 then puts("yes") else puts("no");
if 1 < 2  then puts("yes") else puts("no");
if 2 < 1  then puts("yes") else puts("no");
if 1 > 2  then puts("yes") else puts("no");
if 2 > 1  then puts("yes") else puts("no");
if 1 <= 2 then puts("yes") else puts("no");
if 2 <= 1 then puts("yes") else puts("no");
if 1 <= 1 then puts("yes") else puts("no");
if 1 >= 2 then puts("yes") else puts("no");
if 2 >= 1 then puts("yes") else puts("no");
if 1 >= 1 then puts("yes") else puts("no");
