using printf(string ...): int;

if 1.0 == 1.0 then printf("yes\n") else printf("no\n");
if 1.0 != 1.0 then printf("yes\n") else printf("no\n");
if 1.0 == 2.0 then printf("yes\n") else printf("no\n");
if 1.0 != 2.0 then printf("yes\n") else printf("no\n");
if 1.0 < 2.0  then printf("yes\n") else printf("no\n");
if 2.0 < 1.0  then printf("yes\n") else printf("no\n");
if 1.0 > 2.0  then printf("yes\n") else printf("no\n");
if 2.0 > 1.0  then printf("yes\n") else printf("no\n");
if 1.0 <= 2.0 then printf("yes\n") else printf("no\n");
if 2.0 <= 1.0 then printf("yes\n") else printf("no\n");
if 1.0 <= 1.0 then printf("yes\n") else printf("no\n");
if 1.0 >= 2.0 then printf("yes\n") else printf("no\n");
if 2.0 >= 1.0 then printf("yes\n") else printf("no\n");
if 1.0 >= 1.0 then printf("yes\n") else printf("no\n");
